name: Integrate

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      COMPOSE_FILE: .ci/docker-compose.yml
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print docker and docker-compose version
        run: |
          docker --version
          docker-compose --version

      - name: Setup cache for docker images
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Run unit and integration tests in docker container
        run: docker-compose up

      - name: Print docker-compose config on failure
        run: docker-compose config
        if: failure()

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: prod
          tags: ericdang/python-ci-cd-template:latest
