name: Integrate

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      COMPOSE_FILE: .ci/docker-compose.yml
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup cache for docker images
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Print docker and docker-compose version
        run: |
          docker --version
          docker-compose --version

      - name: Run unit and integration tests in docker container
        run: docker-compose up

      - name: Print docker-compose config on failure
        run: docker-compose config
        # if: failure()
      - name: Print Dockerfile
        run: cat Dockerfile

  push:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup cache for docker images
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # TODO: update tag name
      - name: Build production image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/python-ci-cd-template:latest --target prod .

      - name: Push production image to registry
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/python-ci-cd-template:latest
